# Generated by Django 3.2.25 on 2024-06-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_workspace', '0009_alter_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.URLField()),
                ('image_name', models.CharField(max_length=255)),
                ('default_flavor_name', models.CharField(max_length=50)),
                ('big_flavor_name', models.CharField(max_length=50)),
                ('volume_size', models.IntegerField()),
                ('feature', models.IntegerField()),
            ],
        ),
    ]
