# Generated by Django 3.2.25 on 2024-06-24 08:57

from django.db import migrations

def create_default_vm(apps, schema_editor):
    VM = apps.get_model('researcher_workspace', 'VM')
    VM.objects.create(
        name="Ubuntu 22.04 (Jammy)",
        description="Ubuntu comes with everything you need like an office suite, browsers, email and media apps come pre-installed and thousands more games and applications are available in the Ubuntu Software Centre. Enjoy the simplicity of Ubuntu’s intuitive interface. Fast, secure and with thousands of apps to choose from — for everything you want to do, Ubuntu has what you need.",
        logo="https://object-store.rc.nectar.org.au/v1/AUTH_7235235757f84bf4b748be08a1e8eed5/bumblebee-static/desktop-logos/ubuntu.png",
        image_name="Ubuntu 22.04 LTS (Jammy) Virtual Desktop",
        default_flavor_name="m1.small",
        big_flavor_name="m1.medium",
        volume_size=30,
        feature=1,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('researcher_workspace', '0010_add_default_vm'),
    ]

    operations = [
        migrations.RunPython(create_default_vm),
    ]