# Generated by Django 3.2.25 on 2024-06-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_desktop', '0003_availabilityzone_network_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktoptype',
            name='volume_size',
            field=models.IntegerField(default=30, help_text='Size in GB'),
        ),
    ]
