heat_template_version: 2015-10-15

description: Bumblebee OpenStack component

parameters:
  availability_zone:
    type: string
    description: The NeCTAR zone in which the VMs
    default: melbourne-qh2
  image:
    type: string
    description: ID of image to use for servers (Ubuntu 20.04 LTS (Focal) amd64)
    default: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
  flavor:
    type: string
    description: Flavor to use for servers
    default: m3.medium
  external_network:
    type: string
    description: The Name or ID of the external network to attach the floating IP to
    default: melbourne
    constraints:
      - custom_constraint: neutron.network
  server_count:
    type: number
    description: The number of guacd servers
    default: 3
  zone:
    type: string
    description: DNS zone name or ID
    default: bumblebee.cloud.edu.au.
    constraints:
      - custom_constraint: designate.zone


resources:
  network:
    type: OS::Neutron::Net
    properties:
      name: bumblebee

  subnet:
    type: OS::Neutron::Subnet
    properties:
      name: bumblebee
      dns_nameservers:
        - 1.1.1.1
        - 1.0.0.1
      network: { get_resource: network }
      ip_version: 4
      cidr: 192.168.216.0/22
      allocation_pools:
        - { start: 192.168.216.10, end: 192.168.219.254 }

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: {"network": { get_param: external_network }}
      name: bumblebee

  router_gateway:
    type: OS::Neutron::RouterGateway
    properties:
      router_id: { get_resource: router }
      network_id: { get_param: external_network }

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: router }
      subnet: { get_resource: subnet }

  secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Security group
      name: bumblebee
      rules:
        - remote_group_id: { get_resource: guacd_secgroup }
          remote_mode: remote_group_id
          protocol: tcp
          port_range_min: 3389
          port_range_max: 3389
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp

  guacd_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Security group rules
      name: guacd
      rules:
        - remote_group_id: { get_resource: bastion_secgroup }
          remote_mode: remote_group_id
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 4822
          port_range_max: 4822
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp

  bastion_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Security group rules
      name: guacd
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp

  bastion_port:
    # https://docs.openstack.org/heat/latest/template_guide/openstack.html#OS::Neutron::Port
    type: OS::Neutron::Port
    properties:
      name: bastion
      network: { get_resource: network }
      security_groups:
        - { get_resource: bastion_secgroup }

  bastion_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: external_network }
      port_id: { get_resource: bastion_port }

  bastion_record:
    type: OS::Designate::RecordSet
    properties:
      name: bastion
      type: A
      records:
        - { get_attr: [bastion_floating_ip, floating_ip_address] }
      zone: { get_param: zone }

  cloud_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        timezone: Australia/Melbourne
        disable_root: False
        ssh_pwauth: False
        ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDipJFUTd7T6Pw4T99elfID9stTtmdeogUxcuIZiLFRtUkI6rpoGZYD+c2jGT0NvYWloyB47UPfj8i6DfpSy8AEFNZMlshqJ7fOgafR1m8EQBGYC+xm0fDoeYKJx7DQEWgN4sLgNmnIQNAUqnqLVv+4KuGMvtOWylLpT36kPfDee8TK6/yvwbgb2LSW4NMcVOw1eSRIN5gg7cXY49fXxyopqehVgLNRsjKKXKaECe/kzF0c17XSvYon07XCvzW8lEiDtdr8kymQ950QpIogewKup4t3lSBGH0y602mYHMFri9tla2vBbOOKmWAHBgQJvwKijIK6iSGbrcIGECJD5m3P sam
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnX18eYr4cLaMccq1QJ/dj37z1vtb/NWc5PAbAo6NdX0/Rer4yDew5PbkJEkFR/KIoi5MINN+tPgcuRrxwe018w+LSB1ZUZT/BNVBte2LrQnvAMiHFNH3qtpcCBQn90+ZR8RRLguzK9vGKRxUuSW+4jNbpnqP3pOImjfe4ds54VszRzVPnK+ULgIwm7JILr97aNjFVprgx1nIzyPj3hlzBOF8Kst1bms/cP32o0/kXaQznrw2yWY84LifymF6DnGuhDaJz4KFRWDZoxevWQhqWqvOHw8r5LX2t/NLWzSUq9Sg3TGqPE8R11wtE/n6PXJyvusGlcdhryh8EYLskpKKj andy
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2Z/E3/g5ON1nmYbOZpidvGcw4i4NF6cbCiCjS0WkZDiAlsg6vxHmEI7+XiBYiyAWVBDuqd2qtMYF/mHgwq03VISwj1IFrVy242qbl2zzgnC8w+kQHOtP+kLNidPvj+MVGOTe46qYT1LOEeWUX/EC569KzX/TMYG9pqLO51cVeVcQZeXadP7wHSLBKq9e9peioSCdYR7/sLZZcf3QWRBvYVcijSdFaT/u/OwTETT3CCnuwYM5Xz/YdWR74IhVgpp8co8Obxa2oK9NTia3oxGXnNX0lwFydRmXKkyfSc0bFcH0VxTRPB2Pydf1KPQoMxX6ZK/TxKcliq5+NtGXUt737 jake
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDmqO10QG8evIXQapps4jikvv9jRfaz+qQdsWhZVXmfkpB/ljbthZtIKSI8vzpJR/SXV0o3ERjrEl3h0NV/oTdQKnAQNjKsa8ENRddh37p+PxXy3X3RQRgc7MiuH0+SGlbb3MFo3K+b0nD8DUd+DrloL+h7yL+BK+Xta1+mBuAo9DXbc6x2rZofVvkZfnMbVnqZh3et65KOFZj/cKRqIB2tJU6YzKfnyLrPHAdpaSsKQjRecZh6fibVhWDB7mK2Zb8arZCgEIUaDI7Z7YL+YccBMGwUkkgHqMxMXbmuRIrodxRCHio6O+OUGDm96wTRalQhSUy/TJIEfZgPX6sBkJj9 rocky
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzvI77tP77unpKbIbXuzJ+jFcGzQhrvuTp2x3X6Chhq1Z3eDyb9wPeW04JVw9IBgSsiWYoA3ARH8BhNTFh4RS4SlWp0RnuoR02ZJ+5bYy1m7k3Sxi8dOg14BJP4+8JGPZjZDIqttCYxVhubsqywfnfyVZHX2pYACDKSmyVL6RqfFcGeHjtv28IBiGzmiAgICbgZyr2qi2tHXNieq43pL6GT+9P/OQiDpS+52A+wVMXmOpN381hmzmipHI8WvuYLqU2n8Irivf9nU6OT7XbPEfgeBqpR2JgI8/30artkcUnAPT+QypfbhK61eFuHJCS+PetJBpCB8EZ78tETZsURWZF ade
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBZtBPnPbPr6xf7XUGZ1pwQcdsrIdjbQ3qhhkAbEx+ZQp9JzYnb4JL3PVvVXhD93SGKdLokRV4NBZOFH21xG7/7jclyCDQMN3ymP3P15SIJF2Pkfnp3Xup3vfL6VAUs9obnZtKC0jNz+qUbm9L/LuhTnG00K5BNcNvMZmORi1K3igDfxNhys/zSsNuWnt9zyg8gt0UthQ0LHocMxy6QGHSVTfk76kuOFJxX4nC8fhFby3J7rF+vwery8jLRdzMWokNGOA9d2xzX0p7Bv7TNRwSyh6Se1rm3gf+Dml9CEDVRFeMuxlzISWZB99n3CPfdvWW2hyPomr3lRbDSE4UE1Nh jacob
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmn62XidofySe6KUEMjlqb2hVB6zVuhCthGV3Tk/exvmNqnaNaHv4xmkIwUIj43czQ1dMmaDKN3MzLv/clrddNrcAMaP+G11Ksw71dqXLbJhkR4SuQeYvX2qc0GLQRSkMYsNYd7z1RSFXO8P9LrDTMbVcd+ApxFWJPrkV+tMpPWsLYrIWFAMeYQt+dHHjvU3Rixjm1WZ9SZ7Dv4r9VOtSRAxfPwN2+smnu4UiJzrif/m3A9yEoHA4Q9Sv/cLS39c4lRDVwxkfSRmXc04J+9zqcJHEuofQ0Fv59OB4nEXkwhm56F4JdKpjOpSKX0jACrPqj0O5T+AoPyIh90PqFrAyt scrawley
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII3wUHu7iA/pzeTBX79FlBiKkmOwZiFfoemqQEZqyIuY tim
          - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAh2YqIN5/4Nl9OHsB3HsDuZPfrCN/SvnN1tZD7abqbyPX5Pf9nU7Iu14q2nlEQ26XJatEWrHWuBnSy05jYiS+aK/wYdpTFruhhxVROm3yIgfPvZy/PEWHuicNSC6h92a2lICfPxlPuRVFRef1WHXdwV/nrDpNWJcMB5op53C4stXKJtiaSKJwGsh+bny42oIrIg93zclU9pmEbwEumBNEaPM5mzafEye4km/f0AReW6f8NJJufj05fHUDpbadTfEQgGmGYN7nBLdIsavpxqrZGF3VoSTVyfR9GL0FpNWhaH3gZJy//06XrZpl1RRdZmAi7JkoYJsVJ9c5M+j3A2Qh8w== dylan
        final_message: "The system is finally up, after $UPTIME seconds"

  bastion_server:
    type: OS::Nova::Server
    properties:
      name: bastion
      image: { get_param: image }
      flavor: t3.xsmall
      availability_zone: { get_param: availability_zone }
      networks:
        - port: { get_resource: bastion_port }
      metadata:
        ansible_host_groups: 'bastion'
        ansible_host_vars: 'role=bastion'
      user_data_format: RAW
      user_data: { get_resource: cloud_config }
  wait_handle:
    type: OS::Heat::WaitConditionHandle

  wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: { get_resource: wait_handle }
      count: { get_param: server_count }
      timeout: 600

  guacd_server_group:
    type: OS::Heat::ResourceGroup
    # https://docs.openstack.org/heat/latest/template_guide/openstack.html#OS::Heat::ResourceGroup
    properties:
      count: { get_param: server_count }
      resource_def:
        type: server_member.yaml
        properties:
          name: guacd-%index%
          image: { get_param: image }
          flavor: { get_param: flavor }
          availability_zone: { get_param: availability_zone }
          secgroup: { get_resource: guacd_secgroup }
          network: { get_resource: network }
          subnet: { get_resource: subnet }
          pool: { get_resource: pool }
          port: 4822
          cloud_config: { get_resource: cloud_config }
          wc_notify: { get_attr: ['wait_handle', 'curl_cli'] }

  loadbalancer:
    # https://docs.openstack.org/heat/latest/template_guide/openstack.html#OS::Octavia::LoadBalancer
    type: OS::Octavia::LoadBalancer
    properties:
      vip_subnet: { get_resource: subnet }

  listener:
    type: OS::Octavia::Listener
    # https://docs.openstack.org/heat/latest/template_guide/openstack.html#OS::Octavia::Listener
    properties:
      loadbalancer: { get_resource: loadbalancer }
      protocol: TCP
      protocol_port: 4822
      allowed_cidrs:
        - 172.26.21.0/24
        - 172.26.20.192/26

  pool:
    type: OS::Octavia::Pool
    # https://docs.openstack.org/heat/latest/template_guide/openstack.html#OS::Octavia::Pool
    properties:
      listener: { get_resource: listener }
      lb_algorithm: SOURCE_IP
      protocol: TCP

  monitor:
    # https://docs.openstack.org/heat/latest/template_guide/openstack.html#OS::Octavia::HealthMonitor
    type: OS::Octavia::HealthMonitor
    properties:
      type: TCP
      delay: 3
      timeout: 3
      max_retries: 3
      pool: { get_resource: pool }

  loadbalancer_floating_ip:
    # https://docs.openstack.org/heat/latest/template_guide/openstack.html#OS::Neutron:FloatingIP
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: external_network }
      port_id: { get_attr: [loadbalancer, vip_port_id] }

  loadbalancer_record:
    type: OS::Designate::RecordSet
    properties:
      name: gw
      type: A
      records:
        - { get_attr: [loadbalancer_floating_ip, floating_ip_address] }
      zone: { get_param: zone }

