heat_template_version: rocky

description: Bumblebee Bastion host stack

parameters:
  environment_name:
    type: string
    default: bumblebee
  availability_zone:
    type: string
    default: melbourne-qh2
  image:
    type: string
    constraints:
    - custom_constraint: glance.image
  flavor:
    type: string
    constraints:
    - custom_constraint: nova.flavor
  external_network:
    type: string
    default: melbourne
    constraints:
    - custom_constraint: neutron.network
  server_count:
    type: number
  zone:
    type: string
    constraints:
    - custom_constraint: designate.zone
  oidc_server:
    type: string
  secret:
    type: string
    constraints:
    - custom_constraint: barbican.secret
  db_hostname:
    type: string
  db_name:
    type: string
    default: bumblebee
  db_username:
    type: string
    default: bumblebee
  db_password:
    type: string


resources:

  port:
    # https://docs.openstack.org/heat/latest/template_guide/openstack.html#OS::Neutron::Port
    type: OS::Neutron::Port
    properties:
      name:
        list_join: [ '_', [{ get_param: environment_name }, 'bastion'] ]
      network:
        list_join: [ '_', [{ get_param: environment_name }, 'mgmt'] ]
      security_groups:
      - { list_join: [ '_', [{ get_param: environment_name }, 'bastion'] ] }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: external_network }
      port_id: { get_resource: port }

  recordset:
    type: OS::Designate::RecordSet
    properties:
      name:
        list_join: [ '-', [{ get_param: environment_name }, 'bastion'] ]
      type: A
      records:
      - { get_attr: [floating_ip, floating_ip_address] }
      zone: { get_param: zone }

  cloud_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        timezone: Australia/Melbourne
        runcmd:
        - systemctl disable --now guacd
        - systemctl disable --now tomcat9

  server:
    type: OS::Nova::Server
    properties:
      name:
        list_join: [ '_', [{ get_param: environment_name }, 'bastion'] ]
      image: { get_param: image }
      flavor: { get_param: flavor }
      availability_zone: { get_param: availability_zone }
      networks:
      - port: { get_resource: port }
      user_data_format: RAW
      user_data: { get_resource: cloud_config }

outputs:
  hostname:
    description: Bastion hostname
    value: { get_attr: [recordset, show, name] }
