heat_template_version: rocky

description: Bumblebee AZ network stack

parameters:
  external_network:
    type: string
    constraints:
      - custom_constraint: neutron.network
  cidr:
    type: string
    constraints:
      - custom_constraint: ip_or_cidr


resources:

  network:
    type: OS::Neutron::Net
    properties:
      name: { get_param: "OS::stack_name" }

  subnet:
    type: OS::Neutron::Subnet
    properties:
      name: { get_param: "OS::stack_name" }
      dns_nameservers:
        - 1.1.1.1
        - 1.0.0.1
      network: { get_resource: network }
      ip_version: 4
      cidr: { get_param: cidr }

  router:
    type: OS::Neutron::Router
    properties:
      name: { get_param: "OS::stack_name" }
      external_gateway_info:
        network: { get_param: external_network }

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: router }
      subnet: { get_resource: subnet }

outputs:
  network_cidr:
    description: Network CIDR
    value: { get_attr: [ subnet, cidr ] }
