heat_template_version: rocky

description: Bumblebee OpenStack bash network stack

parameters:
  environment_name:
    type: string
    default: bumblebee
  availability_zone:
    type: string
    default: melbourne-qh2
  image:
    type: string
    constraints:
    - custom_constraint: glance.image
  flavor:
    type: string
    constraints:
    - custom_constraint: nova.flavor
  external_network:
    type: string
    default: melbourne
    constraints:
    - custom_constraint: neutron.network
  server_count:
    type: number
  zone:
    type: string
    constraints:
    - custom_constraint: designate.zone
  oidc_server:
    type: string
  secret:
    type: string
    constraints:
    - custom_constraint: barbican.secret
  db_hostname:
    type: string
  db_name:
    type: string
    default: bumblebee
  db_username:
    type: string
    default: bumblebee
  db_password:
    type: string


resources:

  network:
    type: OS::Neutron::Net
    properties:
      name:
        list_join: [ '_', [{ get_param: environment_name }, 'mgmt'] ]

  subnet:
    type: OS::Neutron::Subnet
    properties:
      name:
        list_join: [ '_', [{ get_param: environment_name }, 'mgmt'] ]
      dns_nameservers:
        - 1.1.1.1
        - 1.0.0.1
      network: { get_resource: network }
      ip_version: 4
      cidr: 192.168.66.0/24

  router:
    type: OS::Neutron::Router
    properties:
      name:
        list_join: [ '_', [{ get_param: environment_name }, 'mgmt'] ]
      external_gateway_info:
        network: { get_param: external_network }

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: router }
      subnet: { get_resource: subnet }

  secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Bumblebee Desktops security group
      name:
        list_join: [ '_', [{ get_param: environment_name }, 'desktops'] ]
      rules:
        - remote_group_id: { get_resource: guacamole_secgroup }
          remote_mode: remote_group_id
          protocol: tcp
          port_range_min: 3389
          port_range_max: 3389
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp

  bastion_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Bastion security group
      name:
        list_join: [ '_', [{ get_param: environment_name }, 'bastion'] ]
      rules:
        - remote_ip_prefix: 128.250.116.128/26  # Core Services desktops
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 172.26.21.0/24  # Management QH2
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 172.26.20.192/26  # Management NP
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 115.146.83.151/32  # RA1
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 115.146.83.72/32  # RA2
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp

  guacamole_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Guacamole security group
      name:
        list_join: [ '_', [{ get_param: environment_name }, 'guacamole'] ]
      rules:
        - remote_group_id: { get_resource: bastion_secgroup }
          remote_mode: remote_group_id
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 8080
          port_range_max: 8080
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp

outputs:
  router_ip:
    description: Management network router IP address
    value: { get_attr: [ router, external_gateway_info, external_fixed_ips, 0, ip_address ] }
  network_cidr:
    description: Network CIDR
    value: { get_attr: [ subnet, cidr ] }
